export { default as stage1 } from './stage1.png'
export { default as stage2 } from './stage2.png'
export { default as stage3 } from './stage3.png'
export { default as stage4 } from './stage4.png'
export { default as stage5 } from './stage5.png'
export { default as stage6 } from './stage6.png'
export { default as stage7 } from './stage7.png'
